### ISSUE TITLE
Use git LFS for large bag files and trained models?

### ISSUE THREAD

**Issue by ruffsl** [angusleigh/leg_tracker#1]
Hello,

Just came across this nice ROS package, and am testing it out now.
I noticed that git pull was taking a while from the repo and then saw you've added large binary bag files to the git repo history. Might I recommend, as this repo still only has 3 commits, to rebase the repo and instead host the bag files via [Git Large File Storage (LFS)](https://git-lfs.github.com/)? This is [free for GitHub](https://github.com/blog/1986-announcing-git-large-file-storage-lfs), under 1GB, which should be more that enough here.

You might also want to do the same with the large opencv random forests yaml files, that way updating the trained models also doesn't incur large repo sizes.

Great project!

**Comment by angusleigh** [comment]
Thanks for the pointer, ruffsl! I wasn't aware of this tool earlier. However, I decided to skip integrating it since it looks like the files are compressed when cloning and only 25MB are transferred in the end. Also, I don't plan on changing those bag files (famous last words :-P).

**Comment by ruffsl** [comment]
>  Also, I don't plan on changing those bag files (famous last words :-P)

Yea, committing binary files was one of my first mistakes starting out with git. Best solved using a revision control method for the job, rather than regretting the bloat later when improving the models weights.
