### ISSUE TITLE
Question in train_leg_detector_res=0.33.launch errors

### ISSUE THREAD

**Issue by qigezai** [angusleigh/leg_tracker#12]
When the program runs the code line , the node breaks out,but no errors are published.No yaml file are saved.
****************************** 
I suspects there may be some bugs lying here(maybe it's not arranging by rows?):
forest_->train(cv::ml::TrainData::create(
      cv::cvarrToMat(cv_data),                // train data 
      cv::ml::ROW_SAMPLE,     // tflag
      cv::cvarrToMat(cv_resp)                // responses (i.e. labels)
      // 0,                      // varldx (?)
      // 0,                      // sampleldx (?)
      // 0,                      // missing data mask
      // var_type                // variable type 
    ));
*******************************
I use opencv3.4

**Comment by angusleigh** [comment]
Let me know if it persists after pulling and retrying.
