### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by batman177** [angusleigh/leg_tracker#13]
Hi, the package.xml file currently specifies a "TODO" license. I saw that some CPP files are under BSD license, but the Python files (e.g. the joint_leg_tracker.py) have no license attached at all. Is this entire repository under the BSD?

Maybe you could add a LICENSE file or a statement in the README to clarify.

**Comment by angusleigh** [comment]
The entire repo should be under BSD. I just added a top-level LICENSE and updated the README to clarify. Let me know if you have other questions/concerns.
