### ISSUE TITLE
when run train_leg_dection.launch crashed~

### ISSUE THREAD

**Issue by gongyue666** [angusleigh/leg_tracker#14]
Hi, when I use my dataset to retrain the leg_tracker, something wrong.
1、in cluster_features.cpp, when the num_points <= 2, repoet an Opencv error.log like this:
OpenCV Error: Bad argument (The function can not solve under-determined linear systems) in solve, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/lapack.cpp, line 1250
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/lapack.cpp:1250: error: (-5) The function can not solve under-determined linear systems in function solve
2、I add a if(num_points <=2) ,and loadPoseData is ok, but  when train(), it crashed angin~

**Comment by angusleigh** [comment]
Hi! The cluster feature calculation assumes there's >= 3 points per cluster, otherwise the geometric features (e.g., linearity, curvature, etc.) don't have much meaning. If you wanted to use <= 2 points, I would recommend turning off the feature calculation altogether.
