### ISSUE TITLE
Tuning for higher frequencies

### ISSUE THREAD

**Issue by duda1202** [angusleigh/leg_tracker#16]
Hi,

I have been using this package to try and follow someone but, the laser I use is of 40Hz and the program does not work well. I down-sampled to 15Hz and still doesn't work as well. Is there anyway I can tune it to 40Hz? Thank you.

**Comment by angusleigh** [comment]
Can you provide any more detailed information on what's not working? I tried it previously with a higher frequency SICK laser and downsampling seemed to work OK. Do you find it has similar performance to the rosbag demos included in the repo?

**Comment by duda1202** [comment]
The issue I have been having is trying to use 15hz. While it detects people, it has a big delay of more than 5 sec between the real position and when it finds the position. And when I try to use in 30 Hz, it is even more. I have been using the throttle from topic_tools to down-sample from 30 to 15. Only the 10Hz and 7.5 Hz have been working properly. 

The performance works similar to the rosbags when using frequencies of 10 or 7.5. Not 15Hz or higher.

**Comment by angusleigh** [comment]
In other words, the detected people are lagging behind the laser points by 5s? That sounds like it's processing delay. The program is rather inefficient since a lot of it is written in Python. Does maybe setting max_detected_clusters to a low value (e.g., 5) help?
