### ISSUE TITLE
 	trained_leg_detector_res=0.33.yaml

### ISSUE THREAD

**Issue by Miaowaaaa** [angusleigh/leg_tracker#19]
Why can't I retrain a model, which could show a similar performance on 'stationary' dataset with the given model? (p.s. I have used the given training code.)

**Comment by angusleigh** [comment]
Can you be more specific? I'm getting similar performance with the when I run
`$ roslaunch leg_tracker train_leg_detector_res\=0.33.launch`
`$ roslaunch leg_tracker demo_stationary_simple_environment.launch`
Albeit, it's not exactly the same. It looks like some adjustment of the related thresholds, like `confidence_threshold_to_maintain_track` would get you there though.
