### ISSUE TITLE
ROS Noetic 

### ISSUE THREAD

**Issue by r0gi** [angusleigh/leg_tracker#24]
Are there any plans to add ROS Noetic support? I think the python 2 -> 3 migration should be trivial but ROS Noetic ships with OpenCV version 4.2.0 instead of 3.2.0, which causes errors upon building the package with catkin_make.

**Comment by Alex-Beh** [comment]
Hi, you can install the opencv 3.4.11 from source. (tutorial is [here](https://linuxize.com/post/how-to-install-opencv-on-ubuntu-20-04/)). Then link to the local Opencv 3 version in the [CMakeLists.txt](https://github.com/RMFHOPE/leg_tracker/blob/676f52cc135c906dd03d79fb1c17e13b6864ce03/CMakeLists.txt#L13). 

I managed to run the training and detection in ROS Noetic with OpenCV version 3.4.11. Hopefully this information can help you.

**Comment by angusleigh** [comment]
Updated in the branch `noetic`. I haven't run extensive tests but I've verified the demo launch files are working with my Ubuntu 20.04, OpenCV 4.2.0, Python 3.8.5 machine.
