### ISSUE TITLE
catkin_make error on train_leg_detector

### ISSUE THREAD

**Issue by YHLok** [angusleigh/leg_tracker#25]
[ 89%] Built target add_two_ints_client
[ 89%] Built target add_two_ints_server
[ 89%] Building CXX object rtabmap_ros/CMakeFiles/rtabmap_wifi_signal_sub.dir/src/WifiSignalSubNode.cpp.o
[ 89%] Linking CXX executable /home/ros/catkin_ws/devel/lib/leg_tracker/train_leg_detector
CMakeFiles/train_leg_detector.dir/src/train_leg_detector.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
train_leg_detector.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x296): undefined reference to `cv::Mat::updateContinuityFlag()'
collect2: error: ld returned 1 exit status
leg_tracker/CMakeFiles/train_leg_detector.dir/build.make:226: recipe for target '/home/ros/catkin_ws/devel/lib/leg_tracker/train_leg_detector' failed
make[2]: *** [/home/ros/catkin_ws/devel/lib/leg_tracker/train_leg_detector] Error 1
CMakeFiles/Makefile2:7304: recipe for target 'leg_tracker/CMakeFiles/train_leg_detector.dir/all' failed
make[1]: *** [leg_tracker/CMakeFiles/train_leg_detector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Linking CXX executable /home/ros/catkin_ws/devel/lib/rtabmap_ros/wifi_signal_sub
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /home/ros/catkin_ws/devel/lib/librtabmap_ros.so, may conflict with libopencv_core.so.3.4
[ 90%] Built target rtabmap_wifi_signal_sub
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed

Hi,
Currently running on ROS Melodic with OpenCV 3.4.2.
This error occur after applying the solution for issue #17 
Any idea on solving this issue, thanks in advance.

**Comment by angusleigh** [comment]
Looks related: https://github.com/jhu-lcsr/handeye_calib_camodocal/issues/22

Also, you could try the new Noetic branch, if you're able to upgrade to Ubunutu 20.04.

**Comment by YHLok** [comment]
Thanks a lot, this seems to solve the issue.
