### ISSUE TITLE
how to use your project build on ROS 1 by ROS 2 

### ISSUE THREAD

**Issue by melaslalib** [angusleigh/leg_tracker#32]
all the code you provide is built according to ROS1. now i have ROS2 i get a lot of problem trying using your project ( and i am beginner) . is that any simple way to do it or i have to change it all?

**Comment by angusleigh** [comment]
No plans to look into ROS2 support at the moment, sorry!

**Comment by melaslalib** [comment]
Thanks so much for ur answers. is that any lineguides to do it byself

**Comment by ncnynl** [comment]
here is ros2 humble for leg_detector https://gitee.com/ncnynl/ros2_leg_detector

**Comment by melaslalib** [comment]
thanks so much
