### ISSUE TITLE
Question in local occupancy grid mapping errors

### ISSUE THREAD

**Issue by LangstonWang** [angusleigh/leg_tracker#7]
Hi, thank you for your useful work, I am learning from your project.
For now, I have retrained followed your guide and used my own bags. However, when I roslaunch one demo bag file similar to your example demo bags, there always a local occupancy grid map error.

error messages:
```
[local_occupancy_grid_mapping-3] process has died [pid 28131, exit code -11, cmd /home/wl/catkin_ws/devel/lib/leg_tracker/local_occupancy_grid_mapping __name:=local_occupancy_grid_mapping __log:=/home/wl/.ros/log/23018c14-ebcf-11e7-b411-8056f2944e1f/local_occupancy_grid_mapping-3.log].
log file: /home/wl/.ros/log/23018c14-ebcf-11e7-b411-8056f2944e1f/local_occupancy_grid_mapping-3*.log
```
and, the so called "******.log"file didn't exist or empty.

There something like some mistakes in local_occupancy_grid_mapping.cpp?
Could you give some advice? Many thanks!

**Comment by angusleigh** [comment]
Are you able to run the demos with the below command?
$ roslaunch leg_tracker demo_stationary_simple_environment.launch 

I haven't seen that error before. It might help if you posted you launch command or any other outputs around that message.

**Comment by MengNan-Li** [comment]
I have the same question. The log file as below. Think your help.
[joint_leg_tracker-2.log](https://github.com/angusleigh/leg_tracker/files/1641461/joint_leg_tracker-2.log)

**Comment by MengNan-Li** [comment]
Now, I change the map size(400* 400) to (200* 200), as result the local_occupancy_grid_mapping can run a few minutes, then it doesn't work(don't run laserAndLegCallback function).
Could you give some advice? Many thanks!

**Comment by angusleigh** [comment]
I haven't found any errors in local_occupancy_grid_mapping.cpp. Would there be any possibility of sending me the rosbags you're using that are causing it to crash?

**Comment by jmill597** [comment]
I had a similar issue with local occupancy grid crashing. I modified the code to get it to work.

In the map update, it was resolving `closest_beam_idx` to `-1`, which causes the `is_sample_human` lookup to crash. I could get around it either by changing the if condition or by ensuring the index is non-negative.

```
+++ b/src/local_occupancy_grid_mapping.cpp
@@ -316,10 +316,12 @@ private:
             bool is_human; 
 
             if (angle > scan.angle_min - scan.angle_increment/2.0 and angle < scan.angle_max + scan.angle_increment/2.0)
+            //if (angle > scan.angle_min and angle < scan.angle_max )
             {
               // Find applicable laser measurement
               double closest_beam_angle = round(angle/scan.angle_increment)*scan.angle_increment;
               int closest_beam_idx = (int)round(angle/scan.angle_increment) + scan.ranges.size()/2;
+              closest_beam_idx = std::max(closest_beam_idx, 0);
               is_human = is_sample_human[closest_beam_idx];
 
               // Processing the range value of the closest_beam to determine if it's a valid measurement or not.
```

**Comment by angusleigh** [comment]
Thanks for the fix, jmill597! Integrated in https://github.com/angusleigh/leg_tracker/commit/41be14c275d89c7877e3f5e0fb99f01e2c2e49d0. Marking this as closed for now.
