### ISSUE TITLE
What is the minimum amount of training data needed?

### ISSUE THREAD

**Issue by FernandezR** [angusleigh/leg_tracker#8]
Hi,

What is the minimum amount of training data needed to retrain the classifier? And how much training data did you use to train the classifier?

Thanks

**Comment by angusleigh** [comment]
The training data is included in the repo [here](https://github.com/angusleigh/leg_tracker/tree/kinetic/rosbags/training_scans_res%3D0.33). I'm not sure how much training data is actually necessary. I think ours comes from 5-10 minutes of data gathing. If you wanted to, you could always plot the test error vs. the amount of training data included to see at what point it seems to be fully saturated.

**Comment by pmirabel** [comment]
In cas anyone struggle with dead link ahead, training rosbags are here : [rosbags/training_scans_res 0.33 ](https://github.com/angusleigh/leg_tracker/tree/melodic/rosbags/training_scans_res%3D0.33 ) (positive not extracted)
