### ISSUE TITLE
Training data - should/can negative datasets include a lot of non-people noise?

### ISSUE THREAD

**Issue by candersen10** [angusleigh/leg_tracker#9]
In the readme for the leg_tracker, it states to "gather negative examples by moving the scanner on a moble platform around empty rooms."

Does this imply that it is best to have the negative dataset in a fairly clean environment?  Or should the negative dataset include a lot of noise (i.e. signs/poles/etc. if used on city streets)?

How environment specific does the negative dataset have to be?  Does the leg tracker need to be retrained for every use case environment?

Thanks!

**Comment by angusleigh** [comment]
FYI, I've included the training data we gathered in [here in the repo](https://github.com/angusleigh/leg_tracker/tree/kinetic/rosbags/training_scans_res%3D0.33), in case you want to just use that.

To your original question: We decided to gather our negative training data in an environment we thought we be most typical for our final application. It include some empty rooms and some rooms filled with chairs and desks. However, it's certaintly possible that performance could be improved by gathering the negative examples in more difficult environments. 

It's difficult to say how well the environments used for gathering the negative dataset need to match your final application environments. I'd guess that as long as your training data includes some walls and other miscellaneous objects, like poles, tables or chairs, it should generalize OK to other domains. You could always test out the effect by gathering lots of training data in different locations and training on some locations and testing on others.

**Comment by candersen10** [comment]
Are you aware of any alternative approaches to this overall method of tracking/following a single person that work by locking onto them and only them rather than being so depending on training data which is specific to certain environments?

We are finding that changes in environments render the algorithm non-functional unless all training data is swapped, especially when walking near objects like poles etc., which it will often view as a cluster and then drop one of your legs/clusters and merge your ID onto the object you are walking past.

So, if you want to use it on a city street, you can't use it in a building, or if you want to use it on a wooded path, you can't use it anywhere else, etc. unless you are swapping the training data for negatives in each different setting.

**Comment by angusleigh** [comment]
I'm surprised the training doesn't generalize well across domains. What happens when you train using all training data from all domains?

For cases where it merges a person cluster with an object, does the local occupancy grid mapping seem to be recognizing the obstacle as such? As in here https://youtu.be/F2Qx3O5AyBs?t=1m18s, you can see that the obstacles are coloured black in the map. After they're marked as such, person tracks should no longer be matched to them.

**Comment by candersen10** [comment]
![image](https://user-images.githubusercontent.com/24898305/36731946-4152269c-1b9a-11e8-9758-f4eac025b68f.png)

We are finding that the local occupancy grid mapping is not recognizing all obstacles.  If you look at the video you shared, for example, you see a detected cluster (see screenshot) which is actually an obstacle but showing up as a cluster (unless someone is standing on one leg there?).

Here is a video of an ID swap as we are seeing it: https://www.youtube.com/watch?v=ehoWwDSPC3U&feature=youtu.be&t=30s.

Any thoughts on how to mitigate this?  In your paper you had mentioned that integrating odometry did not help - do you think integrating it differently might somehow allow for more robust recognition of obstacles as obstacles rather than a clusters/legs?

We have trained using data from multiple domains also.  The false positives training set including multiple environments seems to help to only a small degree (we get best results if we have a training data set pure to one area, but this isn't really possible to do).

Thanks so much for the suggestions by the way!

**Comment by angusleigh** [comment]
In your video, it looks like the local grid occupancy map is fixed to the robot. It should be fixed to the surroundings by compensating for robot ego-motion through odometry, scan matching or SLAM. To demonstrate, try running demo_moving_super_crowded.launch and you'll see the map tends to stay more/less fixed to the walls in the scene. You can also try running with unseen_is_freespace=false to have the local occupancy grid mapping be a little more conservative about what it classifies as free space. 

In general, I think the lowest-hanging fruit to improve the approach (other than including other sensor modalities) is to improve the motion detection and subtraction of static background objects. In our local occupancy grid map, we only use the robot odometery for this, which is a very crude way of compensating for ego-motion. Better would be to integrate scan matching or a SLAM algorithm.
